//
//  FMResourceTable.h
//  client_ios_fm_a
//
//  Created by 杨帆 on 8/29/16.
//  Copyright © 2016 facilityone. All rights reserved.
//
//  用于资源类型定义，存在的意义在于提高查找资源时的效率

#import <Foundation/Foundation.h>

//主题类型
typedef NS_ENUM(NSInteger, FMThemeType) {
    FM_THEME_TYPE_DEFAULT,  //默认主题
    FM_THEME_TYPE_SHANG,    //Shang定制主题
    FM_THEME_TYPE_DTZ,      //DTZ定制主题
};

typedef NS_ENUM(NSInteger, FMResourceType) {
    FM_RESOURCE_TYPE_UNKNOW,    //未知
    
    //颜色
    FM_RESOURCE_TYPE_COLOR_THEME,      //主题色
    FM_RESOURCE_TYPE_COLOR_THEME_HIGHLIGHT, //主题色高亮
    
    //颜色
    FM_RESOURCE_TYPE_COLOR_THEME_N,      //主题色(反色)
    FM_RESOURCE_TYPE_COLOR_THEME_N_HIGHLIGHT, //主题色(反色)高亮
    
    FM_RESOURCE_TYPE_COLOR_MAIN_BLACK,      //黑色
    FM_RESOURCE_TYPE_COLOR_MAIN_WHITE,      //白色
    FM_RESOURCE_TYPE_COLOR_MAIN_GREEN,      //绿色
    FM_RESOURCE_TYPE_COLOR_MAIN_GREEN_HIGHLIGHT,    //
    FM_RESOURCE_TYPE_COLOR_MAIN_BLUE,       //蓝色
    FM_RESOURCE_TYPE_COLOR_MAIN_BLUE_HIGHLIGHT,
    FM_RESOURCE_TYPE_COLOR_MAIN_RED,        //红色
    FM_RESOURCE_TYPE_COLOR_MAIN_RED_HIGHLIGHT,
    FM_RESOURCE_TYPE_COLOR_MAIN_ORANGE,     //橙色
    FM_RESOURCE_TYPE_COLOR_MAIN_ORANGE_HIGHLIGHT,
    FM_RESOURCE_TYPE_COLOR_MAIN_VOILET,     //紫色
    
    FM_RESOURCE_TYPE_COLOR_GRAY_L1,   //#333333
    FM_RESOURCE_TYPE_COLOR_GRAY_L2,   //#474747
    FM_RESOURCE_TYPE_COLOR_GRAY_L3,   //#666666
    FM_RESOURCE_TYPE_COLOR_GRAY_L4,   //#808080
    FM_RESOURCE_TYPE_COLOR_GRAY_L5,   //#999999
    FM_RESOURCE_TYPE_COLOR_GRAY_L6,   //#B3B3B3
    FM_RESOURCE_TYPE_COLOR_GRAY_L7,   //#CCCCCC
    FM_RESOURCE_TYPE_COLOR_GRAY_L8,   //#DDDDDD
    FM_RESOURCE_TYPE_COLOR_GRAY_L9,   //#f0f0f0
    FM_RESOURCE_TYPE_COLOR_GRAY_L10,  //#8a9492
    
    FM_RESOURCE_TYPE_COLOR_MAIN_TEXT,       //主要文字字体色
    FM_RESOURCE_TYPE_COLOR_MAIN_DESC,       //描述文字字体色
    
    FM_RESOURCE_TYPE_COLOR_DEFAULT_LABEL,       //默认的标签颜色
    
    
    FM_RESOURCE_TYPE_COLOR_BACKGROUND,       //输入框默认提示
    FM_RESOURCE_TYPE_COLOR_PLACEHOLDER,       //
    FM_RESOURCE_TYPE_COLOR_RED_DARK,   //深红色
    FM_RESOURCE_TYPE_COLOR_RED_LOGOUT,   //
    FM_RESOURCE_TYPE_COLOR_RED_NOTICE,   //


    FM_RESOURCE_TYPE_COLOR_NAVIGATION_TITLE,   //导航栏标题
    FM_RESOURCE_TYPE_COLOR_MENU_ITEM_COLOR_NORMAL,   //导航栏菜单项文字颜色
    FM_RESOURCE_TYPE_COLOR_MENU_ITEM_COLOR_HIGHLIGHT,   //导航栏菜单项文字颜色，高亮状态
    
    
    FM_RESOURCE_TYPE_COLOR_BOUND,   //边框
    FM_RESOURCE_TYPE_COLOR_BOUND_DOTTED,       //虚线边框
    
    FM_RESOURCE_TYPE_COLOR_ALERT_MENU_ITEM_COLOR_NORMAL,   //弹出式菜单文字颜色
    FM_RESOURCE_TYPE_COLOR_ALERT_MENU_ITEM_COLOR_CANCEL,   //弹出式菜单文字颜色，“取消”颜色
    
    //tabbar
    FM_RESOURCE_TYPE_COLOR_TABBAR_BG,   //tabbar 背景色
    
    //消息
    FM_RESOURCE_TYPE_COLOR_MSG_TITLE,   //消息标题
    FM_RESOURCE_TYPE_COLOR_MSG_PATROL,   //消息，巡检
    FM_RESOURCE_TYPE_COLOR_MSG_ORDER_UNDO,   //待处理工单
    FM_RESOURCE_TYPE_COLOR_MSG_ORDER_APPROVAL,   //待审批工单
    FM_RESOURCE_TYPE_COLOR_MSG_ORDER_DISPACH,   //待派工工单
    FM_RESOURCE_TYPE_COLOR_MSG_REQUIREMENT,   //需求
    FM_RESOURCE_TYPE_COLOR_MSG_INVENTORY,   //库存
    FM_RESOURCE_TYPE_COLOR_MSG_ASSET,   //资产
    FM_RESOURCE_TYPE_COLOR_MSG_MAINTENANCE,   //计划性维护
    
    //离线下载
    FM_RESOURCE_TYPE_COLOR_DOWNLOAD_STATUS_UNDOWNLOADED,   //未下载
    FM_RESOURCE_TYPE_COLOR_DOWNLOAD_STATUS_UNUPDATED,   //未更新
    FM_RESOURCE_TYPE_COLOR_DOWNLOAD_STATUS_DOWNLOADED,   //已下载
    
    //列表
    FM_RESOURCE_TYPE_COLOR_LIST_HEADER_MARK,   //列表头左侧的标记颜色
    
    //计划性维护日历
    FM_RESOURCE_TYPE_COLOR_MAINTENANCE_CALENDAR_SELECT_BG,   //选中日期的背景色
    FM_RESOURCE_TYPE_COLOR_MAINTENANCE_CALENDAR_TEXT_TODAY,   //当天的字体颜色
    FM_RESOURCE_TYPE_COLOR_MAINTENANCE_CALENDAR_TEXT_MONTH,   //当月的字体颜色
    FM_RESOURCE_TYPE_COLOR_MAINTENANCE_CALENDAR_TEXT_OTHER_MONTH,   //其它月份的字体颜色
    
    //工单
    FM_RESOURCE_TYPE_COLOR_ORDER_LABORER_STATUS_UNACCEPT,   //未接单
    FM_RESOURCE_TYPE_COLOR_ORDER_LABORER_STATUS_ACCEPT,   //已接单
    FM_RESOURCE_TYPE_COLOR_ORDER_LABORER_STATUS_BACK,   //已退单
    FM_RESOURCE_TYPE_COLOR_ORDER_LABORER_STATUS_SUBMIT,   //已上交
    
    //弹框
    FM_RESOURCE_TYPE_COLOR_DIALOG_TITLE_BG,       //弹框标题的背景色
    
    FM_RESOURCE_TYPE_COLOR_AUDIO_RECORD,       //录音按钮
    FM_RESOURCE_TYPE_COLOR_AUDIO_CANCEL,       //取消按钮
    //二维码
    FM_RESOURCE_TYPE_COLOR_QRCODE_BOUND,       //
    FM_RESOURCE_TYPE_COLOR_QRCODE_BORDER,       //
    
    //公告
    FM_RESOURCE_TYPE_COLOR_BULLETIN_TYPE_PROJECT,       //项目级
    FM_RESOURCE_TYPE_COLOR_BULLETIN_TYPE_COMPANY,       //公司级
    FM_RESOURCE_TYPE_COLOR_BULLETIN_TYPE_SYSTEM,       //系统级
    FM_RESOURCE_TYPE_COLOR_BULLETIN_TYPE_TOP,       //置顶
};
